# -*- coding: utf-8 -*-
"""devops3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11LM4HJ8V_HPW6Arq7Y710bJBE4i6ndfj
"""

num = int(input("Enter a number: "))
if (num %2) ==0:
  print("Number is even")
else:
  print("Number is odd")

def palindrome(s):
	return s == s[::-1]


# Driver code
s = str(input("Enter a string to check for palindrome:"))
ans = palindrome(s)

if ans:
	print("Yes")
else:
	print("No")